# Generated by Django 5.1.7 on 2025-04-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="mentee",
        ),
        migrations.AddField(
            model_name="session",
            name="capacity",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="session",
            name="mentees",
            field=models.ManyToManyField(
                related_name="group_sessions", to="mentor.profile"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="zoom_link",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
